version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /auth
      - /build
      - /test/integration
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
