version: 2
updates:
  - package-ecosystem: docker
    directory: /build
    schedule:
      interval: weekly
    commit-message:
      prefix: "docker"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
